#!/bin/sh

ssh -p 2201 malallai@malallai.fr "rm -rf /var/www/correction.42.malallai.fr/*; sudo rm -rf /var/www/logs/correction.42.malallai.fr/*; mysql -u root -p -e 'DROP DATABASE ttdeploy'"
scp -r -P 2201 ./* malallai@malallai.fr:/var/www/correction.42.malallai.fr/
