#!/bin/sh

ssh -P 2201 malallai@malallai.fr "rm -rf /var/www/correction.42.malallai.fr/*; mysql -u root -e 'DROP DATABASE camagru'"
scp -P 2201 ./* malallai@malallai.fr:/var/www/correction.42.malallai.fr/