#!/bin/bash
if [ -n "$1" ] ; then 
	rsync -rvz -e 'ssh -p 2201' --progress ./* $1@malallai.fr:/var/www/piscines.42.malallai.fr/rush/rush00
	echo "File copied, access: https://piscines.42.malallai.fr/rush/rush00"
else
	echo "Please provide username."
fi
