<?php
$this->new_post("/Public/assets/pictures/posts/0.jpg");
$this->new_post("/Public/assets/pictures/posts/0.jpg");
$this->new_post("/Public/assets/pictures/posts/0.jpg");
$this->new_post("/Public/assets/pictures/posts/0.jpg");
$this->new_post("/Public/assets/pictures/posts/0.jpg");
$this->new_post("/Public/assets/pictures/posts/0.jpg");
$this->new_post("/Public/assets/pictures/posts/0.jpg");
$this->new_post("/Public/assets/pictures/posts/0.jpg");
$this->new_post("/Public/assets/pictures/posts/0.jpg");
$this->new_post("/Public/assets/pictures/posts/0.jpg");
$this->new_post("/Public/assets/pictures/posts/0.jpg");