#!/bin/bash

RED="\033[38;5;1m"
GREEN="\033[38;5;40m"
YELLOW="\033[38;5;226m"
VERSION=0.0.1
FOLDER=./
FILE=0
MESSAGE=0
PULL=0

while getopts "f:F:m:e:i:vhup" flag
do
	case $flag in

	v)
		printf "${GREEN}%s : %s\n" "Version" ${VERSION}
		exit
		;;
	p)
		PULL=1
		;;
	P)
		PULL=2
		;;
	F)
		FOLDER=$OPTARG
		;;
	f)
		FILE=1
		INCLUDE=$OPTARG
		;;
	m)
		MESSAGE=$OPTARG
		;;
	e)
		FILE=2
		EXCLUDE=$OPTARG
		;;
	i)
		alias "gpush=\"$PWD/$0\""
		echo "alias gpush=\"$PWD/$0\"" >> $OPTARG
		echo "${GREEN}GPush installed"
		exit
		;;
	h)
		echo -e "Help page -- :"
		echo -e "\t-h : Open help page"
		echo -e "\t-v : Print current version"
		echo -e "\t-i : Install GPush alias"
		echo -e "\t-p : Pull without push"
		echo -e "\t-P : Pull and push"
		echo -e "\t-u : Force git pull"
		echo -e "\t-F : Choose git repo folder"
		echo -e "\t-f : File to include from commit (Seperate by ',')"
		echo -e "\t-e : File to exclude from commit (Seperate by ',')"
		echo -e "\t-m : Define commit message"
		exit
		;;
	esac
done

function check_branch {
	git fetch >> /dev/null
	PULL_STATUS=`git status -uno | grep 'git pull'`
	PUSH_STATUS=`git status -u | grep 'git commit'`
	if [ "$PULL_STATUS" != "" ]
	then
		echo "${YELLOW}An update is available for this git repo. (Use '-p' or '-P')"
		if [ "$PULL" == "1" ]; then
			git pull >> /dev/null
			exit
		elif [ "$PULL" == "2" ]; then
			git pull >> /dev/null
		fi
	fi
	if [ "$PUSH_STATUS" == "" ]
	then
		echo "${YELLOW}Nothing to be commit."
		exit
	fi
}

function add_files {
	if [ "$FILE" == "0" ]
	then
		git add . >> /dev/null
	else
		OLDIFS=$IFS
		IFS=','
		if [ "$FILE" == "1" ]
		then
			read -ra array <<< "$INCLUDE"
			for arg in "${array[@]}"; do
				git add $arg >> /dev/null
			done
		else
			read -ra array <<< "$EXCLUDE"
			for arg in "${array[@]}"; do
				git reset -- $arg >> /dev/null
			done
		fi
		IFS=$OLDIFS
	fi
}

function commit_files {
	if [ "$MESSAGE" == "0" ]
	then
		MESSAGE=`git diff --stat --cached origin/master | tail -1`
	fi
	git commit -m "$MESSAGE" >> /dev/null
}

function push_files {
	BRANCH=`git branch | cut -c3-`
	DIFF=`git diff --stat --cached origin/master | tail -1 | cut -d ' ' -f2`
	git push -q
	echo "${YELLOW}Pushed ${GREEN}$DIFF ${YELLOW}modifications, for branch ${GREEN}$BRANCH"
}

cd $FOLDER
check_branch
add_files
commit_files
push_files
